CREATE TABLE PRODUCT_CATEGORY(

PRODUCT_CATEGORY_ID NUMBER PRIMARY KEY,

PRODUCT_CATEGORY_DESC VARCHAR(100) NOT NULL

);

CREATE OR REPLACE VIEW  V_PRODUCT_CATEGORY AS SELECT * FROM PRODUCT_CATEGORY;

 

CREATE TABLE PRODUCT(

PRODUCT_ID NUMBER PRIMARY KEY,

PRODUCT_NAME VARCHAR(100) NOT NULL,

PRODUCT_CATEGORY_ID REFERENCES PRODUCT_CATEGORY(PRODUCT_CATEGORY_ID) ON DELETE CASCADE,

QTY_PER_UNIT NUMBER CHECK(QTY_PER_UNIT > 0),

UNIT_PRICE NUMBER NOT NULL,

PRODUCT_AVAILABLE CHAR(1) NOT NULL

);

CREATE OR REPLACE VIEW  V_PRODUCT AS SELECT * FROM PRODUCT;

 

CREATE TABLE CUSTOMER_CATEGORY(

CUSTOMER_CATEGORY_ID NUMBER PRIMARY KEY,

CUSTOMER_CATEGORY_DESC VARCHAR(100) NOT NULL

);

CREATE OR REPLACE VIEW  V_CUSTOMER_CATEGORY AS SELECT * FROM CUSTOMER_CATEGORY;

 

CREATE TABLE CUSTOMER(

CUSTOMER_ID NUMBER PRIMARY KEY,

CUSTOMER_CATEGORY_ID NUMBER REFERENCES CUSTOMER_CATEGORY(CUSTOMER_CATEGORY_ID) ON DELETE CASCADE,

CUSTOMER_FNAME VARCHAR(100) NOT NULL,

CUSTOMER_LNAME VARCHAR(100) NOT NULL,

CUSTOMER_ADDRESS VARCHAR(100) NOT NULL,

CUSTOMER_PHONE NUMBER NOT NULL,

CUSTOMER_EMAIL VARCHAR(100) NOT NULL

);

CREATE OR REPLACE VIEW  V_CUSTOMER AS SELECT * FROM CUSTOMER;

 

CREATE TABLE OFFERS(

OFFER_ID NUMBER PRIMARY KEY,

OFFER_DESC VARCHAR(100) NOT NULL,

CUSTOMER_CATEGORY_ID REFERENCES CUSTOMER_CATEGORY(CUSTOMER_CATEGORY_ID) ON DELETE CASCADE

);

CREATE OR REPLACE VIEW  V_OFFERS AS SELECT * FROM OFFERS;

 

CREATE TABLE ORDERS(

ORDERS_ID NUMBER PRIMARY KEY,

CUSTOMER_ID NUMBER REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE,

PRODUCT_ID  NUMBER REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,

WARRANTY_ID NUMBER,

OFFER_ID NUMBER REFERENCES OFFERS(OFFER_ID) ON DELETE CASCADE,

ORDER_DATE DATE DEFAULT SYSDATE,

DISPATCH_DATE DATE DEFAULT SYSDATE,

ORDER_PRICE NUMBER NOT NULL,

PAY_STATUS VARCHAR(100) NOT NULL,

ORDER_QTY NUMBER NOT NULL,

INSURANCE_STATUS VARCHAR(100) NOT NULL

);

CREATE OR REPLACE VIEW  V_ORDERS AS SELECT * FROM ORDERS;

 

CREATE TABLE ORDERS_CHANGES_TRACK

   (           ORDERS_ID NUMBER,

               CUSTOMER_ID NUMBER,

               PRODUCT_ID NUMBER,

               WARRANTY_ID NUMBER,

               OFFER_ID NUMBER,

               ORDER_DATE DATE DEFAULT SYSDATE,

               DISPATCH_DATE DATE DEFAULT SYSDATE,

               ORDER_PRICE NUMBER,

               PAY_STATUS VARCHAR2(100),

               ORDER_QTY NUMBER,

               INSURANCE_STATUS VARCHAR(100 ),

               EVENT_TYPE VARCHAR(100)

   )  ;

CREATE TABLE WARRANTY(

WARRANTY_ID NUMBER PRIMARY KEY,

PRODUCT_ID NUMBER REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,

ORDERS_ID NUMBER REFERENCES ORDERS(ORDERS_ID) ON DELETE CASCADE,

START_DATE DATE DEFAULT SYSDATE,

End_DATE DATE DEFAULT SYSDATE

);

CREATE OR REPLACE VIEW  V_WARRANTY AS SELECT * FROM WARRANTY;

 

CREATE TABLE CLAIM_CATEGORY(

CLAIM_CATEGORY_ID NUMBER PRIMARY KEY,

CLAIM_DESCRIPTION VARCHAR(100) NOT NULL

);

CREATE OR REPLACE VIEW  V_CLAIM_CATEGORY AS SELECT * FROM CLAIM_CATEGORY;

 

CREATE TABLE CLAIM(

CLAIM_ID NUMBER PRIMARY KEY,

CLAIM_CATEGORY_ID NUMBER REFERENCES CLAIM_CATEGORY(CLAIM_CATEGORY_ID) ON DELETE CASCADE,

ORDERS_ID NUMBER REFERENCES orders(ORDERS_ID) ON DELETE CASCADE,

WARRANTY_ID VARCHAR(100) NOT NULL,

ISSUE_DATE DATE DEFAULT SYSDATE,

RESOLVE_DATE DATE,

INSURANCE_ID NUMBER

);

CREATE OR REPLACE VIEW  V_CLAIM AS SELECT * FROM CLAIM;



CREATE TABLE COURIER(

COURIER_ID NUMBER PRIMARY KEY,

ORDERS_ID NUMBER REFERENCES orders(ORDERS_ID) ON DELETE CASCADE,

COURIER_NAME VARCHAR(100) NOT NULL,

DELIVERY_STATUS VARCHAR(100) NOT NULL,

PAY_STATUS VARCHAR(100) NOT NULL

);

CREATE OR REPLACE VIEW  V_COURIER AS SELECT * FROM COURIER;

 

CREATE TABLE INSURANCE_PRICE(

INSURANCE_PRICE_ID NUMBER PRIMARY KEY,

PRODUCT_ID REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,

PRODUCT_CATEGORY_ID REFERENCES PRODUCT_CATEGORY(PRODUCT_CATEGORY_ID) ON DELETE CASCADE,

INSURANCE_PRICE NUMBER NOT NULL

);

CREATE OR REPLACE VIEW  V_INSURANCE_PRICE AS SELECT * FROM INSURANCE_PRICE;

 

CREATE TABLE INSURANCE(

INSURANCE_ID NUMBER PRIMARY KEY,

INSURANCE_START_DATE DATE DEFAULT SYSDATE,

INSURANCE_END_DATE DATE DEFAULT ADD_MONTHS(SYSDATE,12),

ORDERS_ID REFERENCES ORDERS(ORDERS_ID) ON DELETE CASCADE,

INSURANCE_PRICE_ID REFERENCES INSURANCE_PRICE(INSURANCE_PRICE_ID) ON DELETE CASCADE

);

CREATE OR REPLACE VIEW  V_INSURANCE AS SELECT * FROM INSURANCE;

